---
- hosts: build
  become: true
  tasks:
  - name: update ubuntu repo and cache
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  - name: install java v17
    apt:
      name: openjdk-17-jre
      state: present
  - name: download maven package
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /opt
  - name: unarchive maven package
    unarchive:
      src: /opt/apache-maven-3.9.9-bin.tar.gz
      dest: /opt
      remote_src: yes

  - name: Install required dependencies for docker
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker repo
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
  - name: Install Docker package
    apt:
      name: docker-ce
      state: present
      update_cache: yes
  - name: Add user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes
  - name: Ensure docker service
    service:
      name: docker
      state: started
      enabled: yes
  - name: change permission for docker.sock
    file:
      path: /var/run/docker.sock
      owner: root
      group: docker
      mode: '0660'
  - name: Apply new group membership
    shell: newgrp docker && docker ps
    register: docker_access
    changed_when: false

  - name: Print docker access result
    debug:
      msg: "Docker access verification: {{ docker_access.stdout }}"

  - name: Restart docker service to apply changes
    service:
      name: docker
      state: restarted