---
- hosts: jenkins-slave
  become: true
  tasks:
  - name: update ubuntu repo and cache
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  - name: install java v17
    apt:
      name: openjdk-17-jre
      state: present
  - name: download maven package
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /opt
  - name: unarchive maven package
    unarchive:
      src: /opt/apache-maven-3.9.9-bin.tar.gz
      dest: /opt
      remote_src: yes