  - name: Pull Sonarqube Docker image
    docker_image:
      name: "{{ sonarqube_image }}"
      source: pull

  - name: Run Sonarqube container
    docker_container:
      name: "{{ sonarqube_container_name }}"
      image: "{{ sonarqube_image }}"
      ports:
        - "{{ sonarqube_port }}:9090"
      env:
        SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      volumes:
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_logs:/opt/sonarqube/logs
        - sonarqube_extensions:/opt/sonarqube/extensions
      restart_policy: always
      state: started
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000"]
        interval: 30s
        retries: 3

  - name: Verify Sonarqube container is running
    command: "docker ps -q -f name=sonarqube"
    register: sonarqube_running
    failed_when: sonarqube_running.stdout == ""

  - name: check Sonarqube service on port 9000
    wait_for:
      host: "127.0.0.1"
      port: 9000
      timeout: 60
      state: started